### ISSUE TITLE
nectar consumes copious amounts of (virtual) memory

### ISSUE THREAD

**Issue by ldeffenb** [bzznectar/nectar#2]
Shortly after getting my nectar node up and running, I noticed that it was consuming 72% of my 32GB RAM, impacting the two co-resident bee nodes which only occupy 6% or 7%.  After terminating and restarting nectar, it still grows steadily until it begins negatively impacting the host performance.

I don't know if this is stacking goroutines caused by the lack of synchronization described in #1 or if there are other factors at work consuming memory.  But this really should be addressed because at the rate it grows, a 256GB+ machine may be required just to run a single nectar node!

**Comment by ldeffenb** [comment]
This seems to be an issue with the initial creation of the "reverse storage space" as my node has returned to a reasonable memory consumption now that it has achieved "harvest service" in the logs.

**Comment by bzznectar** [comment]
The new version has been optimized
